server:
  port: 2333
  address: 0.0.0.0

plugins:
  youtube:
    enabled: true
    version: "1.18.0"
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TV
      - WEB
      - MWEB
    oauth:
      enabled: true
      refreshToken: "1//06YBdt0IZJPsZCgYIARAAGAYSNwF-L9Ire_iXA_8YXrviON32U1leT8rNiGCa13KrdtgKUqm6remqTmEY4Bh57mkVqmHpfQZX9_g"

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      snapshot: false
  server:
    password: "gkhmusic"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: true
      http: true
      local: false
